create table loveland (
  ogc_fid serial primary key,
  geoid text,
  sourceagent text,
  parcelnumb text,
  usecode text,
  usedesc text,
  struct boolean,
  multistruct boolean,
  structno integer,
  yearbuilt integer,
  numstories double precision,
  numunits integer,
  structstyle text,
  parvaltype text,
  improvval double precision,
  landval double precision,
  parval double precision,
  agval double precision,
  saleprice double precision,
  saledate date,
  taxamt double precision,
  owntype text,
  owner text,
  ownfrst text,
  ownlast text,
  subsurfown text,
  subowntype text,
  mailadd text,
  address text,
  saddno text,
  saddpref text,
  saddstr text,
  saddsttyp text,
  saddstsuf text,
  sunit text,
  scity text,
  city text,
  county text,
  state2 text,
  szip text,
  legaldesc text,
  subdivision text,
  sourceref text,
  sourcedate date,
  sourceurl text,
  recrdareatx text,
  recrdareano double precision,
  gisacre double precision,
  reviseddate date,
  path text
);
